services:
  app:
    build: .
    command: ["streamlit", "run", "app.py"]
    volumes:
      - .:/app
    tty: true
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8501:8501"
      - "8888:8888"
    networks:
      - graphrag
  #  neo4j:
  #    image: neo4j:5.26.6
  #    container_name: neo4j
  #    ports:
  #      - "7474:7474"
  #      - "7687:7687"
  #    volumes:
  #      - ./neo4j/data:/data
  #    environment:
  #      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
  #    networks:
  #      - graphrag
  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:1.3.7
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./server/rag_storage:/app/data/rag_storage
      - ./server/inputs:/app/data/inputs
      - ./server/config.ini:/app/config.ini
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
      - LLM_BINDING_HOST=${API_HOST}
      - LLM_BINDING_API_KEY=${API_KEY}
      - EMBEDDING_BINDING_HOST=${API_HOST}
      - EMBEDDING_BINDING_API_KEY=${API_KEY}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - graphrag

networks:
  graphrag:
    driver: bridge
